# Site
name: "Defenz.io"
title: "Blog"
description: "Driving the Future of Cybersecurity Through Collaboration."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
banner: 'assets/images/banner.png'
url: https://blog.defenz.io
#baseurl: /blog
#google_analytics: 'UA-46278016-1'
#disqus: 'defenzblog'
#mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dadash:
    name: nam3lum
    display_name: nam3lum
    avatar: "assets/images/nam3lum.jpeg"
    email: dadash.guliyev@defenz.io
    web: https://defenz.io
    twitter: https://twitter.com/nam3lum
    description: "Cybersecurity Engineer"
  # example:
  #   name: example
  #   display_name: example
  #   avatar: "assets/images/example.jpeg"
  #   gravatar: gravatarid
  #   email: example@example.io
  #   web: 
  #   twitter: https://twitter.com/nam3lum
  #   description: "Cybersecurity Engineer"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 15
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-000000000"
adsense-data-ad-slot: "0000000"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
